using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace RadioWebControl.Core.Services
{
    /// <summary>
    /// Writes ADIF records, which is the other half of <see cref="AdifParser"/>.
    ///
    /// ADIF is length-prefixed rather than delimited - a field is
    /// <c>&lt;NAME:LENGTH&gt;value</c> - so the one thing a writer must get
    /// right is that LENGTH is the length of the value as it will be read back.
    /// That is bytes, not characters: the specification is explicit that the
    /// count is octets, and a callsign or a comment containing anything outside
    /// ASCII will be silently truncated by every reader if the count is taken
    /// from <c>string.Length</c>. Nothing in a CW QSO ought to be non-ASCII, but
    /// the comment field is free text an operator types, and "ought to" is not a
    /// guarantee. It is counted in UTF-8 bytes here.
    ///
    /// The output is deliberately plain: one record per line, uppercase field
    /// names, no type indicators. Log4OM and GridTracker both watch ADIF files,
    /// so writing one reaches those users without an integration.
    ///
    /// One asymmetry worth knowing about: <see cref="AdifParser"/> counts that
    /// length in <em>characters</em>, so a value with anything outside ASCII in
    /// it would round-trip through our own parser desynchronised. Everything
    /// this writer is used for is ASCII, and the parser only reads CALL, FREQ,
    /// MODE and BAND - all of which are - so nothing is broken today. The
    /// writer follows the specification rather than matching the parser's bug,
    /// because third-party loggers follow the specification too.
    /// </summary>
    public static class AdifRecordWriter
    {
        /// <summary>
        /// A single logged contact. Everything is optional except the callsign,
        /// because a QSO record with no callsign is not a record of anything.
        /// </summary>
        public sealed class Qso
        {
            public string  Callsign      { get; set; } = string.Empty;
            public DateTime WhenUtc      { get; set; } = DateTime.UtcNow;
            public DateTime? EndUtc      { get; set; }

            /// <summary>Megahertz, as ADIF wants it - the app holds Hz.</summary>
            public double? FrequencyMhz  { get; set; }
            public string? Band          { get; set; }
            public string? Mode          { get; set; } = "CW";
            public string? RstSent       { get; set; }
            public string? RstReceived   { get; set; }
            public string? Name          { get; set; }
            public string? Qth           { get; set; }
            public string? Comment       { get; set; }
            public string? StationCall   { get; set; }
            public string? OperatorCall  { get; set; }
        }

        /// <summary>
        /// The header ADIF wants at the top of a file. Written once, when the
        /// file is created; appending to an existing log must not repeat it.
        /// </summary>
        public static string Header(string programName, string programVersion)
        {
            var sb = new StringBuilder();
            sb.Append("Generated by ").Append(programName).Append('\n');
            Field(sb, "ADIF_VER", "3.1.4");
            Field(sb, "PROGRAMID", programName);
            Field(sb, "PROGRAMVERSION", programVersion);
            sb.Append("<EOH>\n");
            return sb.ToString();
        }

        /// <summary>One record, terminated with &lt;EOR&gt; and a newline.</summary>
        public static string Write(Qso qso)
        {
            if (qso is null) throw new ArgumentNullException(nameof(qso));
            if (string.IsNullOrWhiteSpace(qso.Callsign))
                throw new ArgumentException("A QSO record needs a callsign.", nameof(qso));

            var sb = new StringBuilder();
            Field(sb, "CALL",        qso.Callsign.Trim().ToUpperInvariant());
            Field(sb, "QSO_DATE",    qso.WhenUtc.ToString("yyyyMMdd", CultureInfo.InvariantCulture));
            Field(sb, "TIME_ON",     qso.WhenUtc.ToString("HHmmss",   CultureInfo.InvariantCulture));
            if (qso.EndUtc is { } end)
                Field(sb, "TIME_OFF", end.ToString("HHmmss", CultureInfo.InvariantCulture));

            // ADIF wants MHz to six decimal places. "F6" rather than "R" so a
            // frequency never comes out in exponential notation, which readers
            // reject, and InvariantCulture so a European decimal comma - which
            // several of the operators using this app have - cannot get in.
            if (qso.FrequencyMhz is { } mhz && mhz > 0)
                Field(sb, "FREQ", mhz.ToString("F6", CultureInfo.InvariantCulture));

            // The band is derivable from the frequency and a logger will reject
            // a record whose BAND and FREQ disagree, so derive it rather than
            // asking the caller to keep two fields in step. An explicit Band
            // still wins: an operator working cross-band split knows better.
            Field(sb, "BAND", qso.Band
                              ?? (qso.FrequencyMhz is { } f && f > 0 ? BandFor(f) : null));
            Field(sb, "MODE",        qso.Mode);
            Field(sb, "RST_SENT",    qso.RstSent);
            Field(sb, "RST_RCVD",    qso.RstReceived);
            Field(sb, "NAME",        qso.Name);
            Field(sb, "QTH",         qso.Qth);
            Field(sb, "COMMENT",     qso.Comment);
            Field(sb, "STATION_CALLSIGN", qso.StationCall);
            Field(sb, "OPERATOR",    qso.OperatorCall);
            sb.Append("<EOR>\n");
            return sb.ToString();
        }

        private static void Field(StringBuilder sb, string name, string? value)
        {
            if (string.IsNullOrWhiteSpace(value)) return;

            // A newline inside a value would end the record for a line-oriented
            // reader even though ADIF itself does not care, so collapse any
            // whitespace run to a single space. A comment is the field an
            // operator types into, and typing a newline into it is easy.
            var clean = string.Join(" ", value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
            if (clean.Length == 0) return;

            sb.Append('<').Append(name).Append(':')
              .Append(Encoding.UTF8.GetByteCount(clean).ToString(CultureInfo.InvariantCulture))
              .Append('>').Append(clean).Append(' ');
        }

        /// <summary>
        /// The ADIF band name for a frequency in MHz, or null off any band.
        ///
        /// Edges are the IARU/ADIF band limits rather than any one region's
        /// allocation, because the field says which band the contact was on,
        /// not whether the operator was licensed for it. 60 m is the ragged
        /// one - it is channelised in most countries and a contiguous slice in
        /// others - so the ADIF-defined 5.06-5.45 range is used whole.
        /// </summary>
        public static string? BandFor(double mhz)
        {
            foreach (var (lo, hi, name) in Bands)
                if (mhz >= lo && mhz <= hi) return name;
            return null;
        }

        private static readonly (double Lo, double Hi, string Name)[] Bands =
        {
            (0.1357,  0.1378,  "2190m"),
            (0.472,   0.479,   "630m"),
            (1.8,     2.0,     "160m"),
            (3.5,     4.0,     "80m"),
            (5.06,    5.45,    "60m"),
            (7.0,     7.3,     "40m"),
            (10.1,    10.15,   "30m"),
            (14.0,    14.35,   "20m"),
            (18.068,  18.168,  "17m"),
            (21.0,    21.45,   "15m"),
            (24.89,   24.99,   "12m"),
            (28.0,    29.7,    "10m"),
            (40.0,    45.0,    "8m"),
            (50.0,    54.0,    "6m"),
            (70.0,    71.0,    "4m"),
            (144.0,   148.0,   "2m"),
        };
    }
}
