using RadioWebControl.Core.Services;

namespace RadioWebControl.Core.Tests;

// First tests in the shared core. AdifParser is a pure function with no DOM,
// no radio and no I/O, which is exactly why it and calibration-engine were
// chosen as the first tenants — see the shared-core plan, phase 2.
public class AdifParserTests
{
    // ---- Parse ----

    [Fact]
    public void Parse_Null_ReturnsEmpty()
    {
        Assert.Empty(AdifParser.Parse(null!));
        Assert.Empty(AdifParser.Parse(""));
    }

    [Fact]
    public void Parse_SingleRecord_ReadsAllFourFields()
    {
        var adif = "<CALL:6>MM5AGM<FREQ:6>14.074<MODE:3>FT8<BAND:3>20M<EOR>";

        var recs = AdifParser.Parse(adif);

        var r = Assert.Single(recs);
        Assert.Equal("MM5AGM", r.Callsign);
        Assert.Equal("14.074", r.Frequency);
        Assert.Equal("FT8", r.Mode);
        Assert.Equal("20M", r.Band);
    }

    [Fact]
    public void Parse_SkipsHeaderBeforeEoh()
    {
        // Anything before <EOH> is header and must not become a record.
        var adif = "Generated by something <PROGRAMID:4>TEST<EOH>" +
                   "<CALL:6>MM5AGM<MODE:3>SSB<EOR>";

        var r = Assert.Single(AdifParser.Parse(adif));
        Assert.Equal("MM5AGM", r.Callsign);
        Assert.Equal("SSB", r.Mode);
    }

    [Fact]
    public void Parse_MultipleRecords_And_TrailingRecordWithoutEor()
    {
        // Second record has no closing <EOR> — the parser is documented to
        // still emit it.
        var adif = "<CALL:5>G0ABC<EOR><CALL:5>G0XYZ";

        var recs = AdifParser.Parse(adif);

        Assert.Equal(2, recs.Count);
        Assert.Equal("G0ABC", recs[0].Callsign);
        Assert.Equal("G0XYZ", recs[1].Callsign);
    }

    [Fact]
    public void Parse_IgnoresTypeSuffix_And_IsCaseInsensitiveOnFieldNames()
    {
        // "<call:5:S>" — mixed case, and a type indicator after the length.
        var adif = "<call:5:S>MM5AG<eor>";

        var r = Assert.Single(AdifParser.Parse(adif));
        Assert.Equal("MM5AG", r.Callsign);
    }

    [Fact]
    public void Parse_EmptyRecord_IsNotEmitted()
    {
        // <EOR> with no fields in between contributes nothing.
        var recs = AdifParser.Parse("<EOR><CALL:5>MM5AG<EOR>");
        Assert.Single(recs);
    }

    // ---- FreqMHzToHz ----

    [Theory]
    [InlineData("14.074", 14_074_000L)]
    [InlineData("7", 7_000_000L)]
    [InlineData("0.475", 475_000L)]
    public void FreqMHzToHz_ParsesDecimalMHz(string mhz, long expectedHz)
    {
        Assert.Equal(expectedHz, AdifParser.FreqMHzToHz(mhz));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("not-a-number")]
    [InlineData("0")]
    [InlineData("-1")]
    public void FreqMHzToHz_RejectsBadInput(string? bad)
    {
        Assert.Null(AdifParser.FreqMHzToHz(bad));
    }

    // ---- AdifModeToRadioMode ----

    [Theory]
    [InlineData("USB", "USB")]
    [InlineData("LSB", "LSB")]
    [InlineData("AM", "AM")]
    [InlineData("FM", "FM")]
    [InlineData("CW", "CW-U")]
    [InlineData("RTTY", "RTTY-L")]
    [InlineData("FT8", "DATA-U")]
    [InlineData("PSK31", "DATA-U")]
    [InlineData("data", "DATA-U")]   // case-insensitive
    public void AdifModeToRadioMode_MapsKnownModes(string adif, string expected)
    {
        Assert.Equal(expected, AdifParser.AdifModeToRadioMode(adif));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("SOMETHING-NEW")]
    public void AdifModeToRadioMode_DefaultsToUsb(string? unknown)
    {
        Assert.Equal("USB", AdifParser.AdifModeToRadioMode(unknown));
    }
}
